### ISSUE TITLE
Build failures on ARM machines running Xcode 14-15

### ISSUE THREAD

**Issue by emendelson** [kanjitalk755/macemu#189]
I can build current macemu code on an Intel Mac running Monterey and Xcode 14.2, but when I try to build the same code on Sonoma (on an ARM Mac), running Xcode 15.0.1, the SheepShaver build command-line fails with this error:

```
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Preprocess\ Info.plist /Users/edward/Desktop/macemu-master/SheepShaver/src/MacOSX/build/SheepShaver_Xcode8.build/Release/SheepShaver.build/Script-08CD3F3214B665E1009CA2A2.sh (in target 'SheepShaver' from project 'SheepShaver_Xcode8')
(1 failure)
```

And the BasiliskII command-line fails with this:

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/edward/Desktop/macemu-master/BasiliskII/src/MacOSX/build/uae_cpu_2021.build/Release/uae_cpu_arm64.build/Objects-normal/arm64/newcpu.o /Users/edward/Desktop/macemu-master/BasiliskII/src/uae_cpu_2021/newcpu.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'uae_cpu_arm64' from project 'uae_cpu_2021')
	CompileC /Users/edward/Desktop/macemu-master/BasiliskII/src/MacOSX/build/uae_cpu_2021.build/Release/uae_cpu_arm64.build/Objects-normal/arm64/fpu_mpfr.o /Users/edward/Desktop/macemu-master/BasiliskII/src/uae_cpu_2021/fpu/fpu_mpfr.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'uae_cpu_arm64' from project 'uae_cpu_2021')
(2 failures)

```

**Comment by emendelson** [comment]
The build also fails under Xcode 14.3.1 under Ventura (ARM).

**Comment by kanjitalk755** [comment]
SheepShaver:
Fixed.

BasiliskII:
Didn't reproduced.
Since the error is related to `MPFR`, re-install `GMP` and `MPFR`, then try again.

**Comment by RonaldPR** [comment]
I couldn't reproduce the build issue with BasiliskII either. Yesterday, before the fix for SheepShaver, BasiliskII build succeeded smoothly on my M1 iMac with macOS 14.1.2 and Xcode 15.0.1.

**Comment by emendelson** [comment]
You are right about BasiliskII; I reinstalled `GMP` and `MPFR` and built successfully.

But I still get this error with SheepShaver, using the current code, downloaded via Git:

```
warning: Run script build phase 'Preprocess Info.plist' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'SheepShaver' from project 'SheepShaver_Xcode8')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'SheepShaver' from project 'SheepShaver_Xcode8')
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/edward/Library/CloudStorage/Dropbox/macemu/SheepShaver/src/MacOSX/build/SheepShaver_Xcode8.build/Release/kpx_cpu.build/Objects-normal/arm64/sheepshaver_glue.o /Users/edward/Library/CloudStorage/Dropbox/macemu/SheepShaver/src/kpx_cpu/sheepshaver_glue.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'kpx_cpu' from project 'SheepShaver_Xcode8')
(1 failure)
```

I must be doing something wrong, but I can't guess what it is. Sonoma 14.1.2, ARM Mac, Xcode 15.0.1.

**Comment by RonaldPR** [comment]
Building SheepShaver from the latest code also fails here:
```
The following build commands failed:
	CompileC /Users/ronald/Desktop/macemu-master/SheepShaver/src/MacOSX/build/SheepShaver_Xcode8.build/Release/kpx_cpu.build/Objects-normal/x86_64/sheepshaver_glue.o /Users/ronald/Desktop/macemu-master/SheepShaver/src/kpx_cpu/sheepshaver_glue.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'kpx_cpu' from project 'SheepShaver_Xcode8')
(1 failure)
```
There was also this warning (related to the fix for hard cursor in full screen?)
```
/Users/ronald/Desktop/macemu-master/SheepShaver/src/Unix/sysdeps.h:307:9: warning: 
      implicit conversion loses integer precision: 'long' to 'int'
      [-Wshorten-64-to-32]
        return ret;
        ~~~~~~ ^~~
```
M1 iMac, macOS 14.1.2, Xcode 15.0.1, SDL2 2.28.5.

**Comment by kanjitalk755** [comment]
Fixed.

**Comment by emendelson** [comment]
Yes. Thank you!!

**Comment by kanjitalk755** [comment]
The OS and Xcode versions are the same, but doesn't reproduced.

**Comment by EdoardoLaGreca** [comment]
I removed the cloned repo, cloned it again, installed `sdl2` (also `gmp` and `mpfr`, just in case) from Homebrew. I noticed that the error is still there when I run `xcodebuild`, so I investigated further and I noticed the following error:

```
/Users/edo/vm/emu/macemu/SheepShaver/src/kpx_cpu/sheepshaver_glue.cpp:50:10: fatal error: 
      'SDL_events.h' file not found
#include <SDL_events.h>
         ^~~~~~~~~~~~~~
16 warnings and 1 error generated.
```

I checked the files installed with the package `sdl2` (command: `brew ls sdl2`). `SDL_events.h` has been installed, but it was installed in `/opt/homebrew/Cellar/sdl2/2.30.3/include/SDL2/`.

My guess is that Xcode does not search for include files in that path, so it should be added in the Xcode project. Could you please add it?

**Comment by RonaldPR** [comment]
Do not use homebrew to install needed additional files. Use the instruction provided by kanjitalk755 here.

Also gmp and mpfr (needed for BasiliskII, not for SheepShaver) will not work correctly when installed through homebrew.

SDL2.framework should be installed in /Library/Frameworks/

SDL2-2.30.3.dmg kan be downloaded from https://github.com/libsdl-org/SDL/releases/tag/release-2.30.3
